update_fastlane

default_platform(:ios)

# Default temporary keychain password and name, if not included from environment
TEMP_KEYCHAIN_NAME_DEFAULT = "fastlane_flutter"
TEMP_KEYCHAN_PASSWORD_DEFAULT = "temppassword"
APP_ID = "1:281246973237:ios:b59a874163fc37a903607c"
FIREBASE_TOKEN = "1//0fkD5PaN39-eCCgYIARAAGA8SNwF-L9Iru_cgX28F2G7zFyk9KEeLvu8RPhQx2-HQYcTRR2fTk79UH_1E8h1YvEZ3ngZVtMwd-pc"

# Remove the temporary keychain, if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

# Create the temporary keychain with name and password
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

# Ensure we have a fresh, empty temporary keychain
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Build & sign iOS app"
  lane :build_ios do |options|
    disable_automatic_code_signing(
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AdHoc #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution"
    )
    keychain_name = TEMP_KEYCHAIN_NAME_DEFAULT
    keychain_password = TEMP_KEYCHAN_PASSWORD_DEFAULT
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      type: "adhoc",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: "https://github.com/ajgreenman/ios-certificates.git"
    )
    build_ios_app(
      export_options: {
          method: "ad-hoc"
      },
      output_directory: "./build/Runner"
    )
    delete_temp_keychain(keychain_name)
  end

  desc "Deploy a new beta"
  lane :distribute_beta do |options|
    # Upload to test flight or AppStore depending on caller parameters
    firebase_app_distribution(
          app: APP_ID,
          groups: "iOS",
          release_notes: "v0.1",
          firebase_cli_path: "/usr/local/bin/firebase",
          firebase_cli_token: FIREBASE_TOKEN,
          ipa_path: "./build/Runner/Strava Stats.ipa"
      )
  end
end